export const trackers = {
  categories: {
    Analytics: [
      "63squares.com",
      "abtasty.com",
      "3dstats.com",
      "addfreestats.com",
      "adobedc.net",
      "livefyre.com",
      "mktoresp.com",
      "sitestat.com",
      "google-analytics.com",
      "analytics.google.com",
      "mixpanel.com",
      "segment.io",
      "amplitude.com",
      "hotjar.com",
      "mouseflow.com",
      "crazyegg.com",
    ],
    Social: [
      "facebook.com",
      "facebook.net",
      "twitter.com",
      "linkedin.com",
      "instagram.com",
      "pinterest.com",
    ],
    ConsentManagers: [
      "cookiebot.com",
      "onetrust.com",
      "osano.com",
      "privacymanager.io",
    ],
    Email: [
      "mailchimp.com",
      "sendgrid.net",
      "mailgun.com",
      "constant.contact.com",
    ],
    Advertising: [
      "doubleclick.net",
      "google-adservices.com",
      "googleadservices.com",
      "googlesyndication.com",
      "adsystem.com",
      "adnxs.com",
      "adroll.com",
      "criteo.com",
      "outbrain.com",
      "taboola.com",
    ],
  },
};
